/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"

#include "uart.h"
#include "eeprom.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	char str[90];
	int choice ;
	char str1[90];

	SystemInit();
	UartInit(BAUD_9600);
    EEPROM_Init();

	do
	{
		sprintf(str," \n\r Menu : \n\r. Write String : 1\n\r .Read String : 2\n\r");
		UartPuts(str);

		sprintf(str,"select your choice ");
		UartPuts(str);
		UartGets(str);

		sscanf(str,"%d",&choice);

		switch(choice) {

		case 0 :
			sprintf(str,"\n\r Thank You ! \n\r");
			UartPuts(str);
			break;

		case 1 :
			sprintf(str,"\n\rEnter the String : ");
			UartPuts(str);
			UartGets(str);
			sscanf(str,"%s",str1);
			EEPROM_Write(0x0020,(uint8_t*)str1,32);
			break ;

		case 2 :
			sprintf(str,"\n\rRead the string : \n\r");
			UartPuts(str);
			EEPROM_Read(0x0020,(uint8_t*)str1,32);
			UartPuts(str1);
		//	sprintf(str1,"\n\r");
		//	UartPuts(str);
			break ;

		default :
			sprintf(str,"Invalid Choice !");
			UartPuts(str);

		}

	}

while(choice !=0);

	while(1);


	return 0;
}
